name = "next-blog"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "next-blog-db"
database_id = "" # 请将这里替换为您实际的数据库 ID

[site]
bucket = ".next" 